language: cpp
os:
 - linux
script: 
 - mkdir -p build && cd build
 - cmake ..
 - make -j 2
compiler: 
 - gcc

 
before_install:
 - sudo apt-get update
 - sudo apt-get -y install libboost-all-dev libspdlog-dev
 
install:
 - cd ..
 - wget --no-check-certificate http://www.accellera.org/images/downloads/standards/systemc/systemc-2.3.3.tar.gz
 - tar xfvz systemc-2.3.3.tar.gz
 - cd systemc-2.3.3
 - mkdir build && cd build
 - ../configure  CXXFLAGS="-std=c++11"
 - make -j 4 && make install
 - cd ../..
 - rm -r systemc-2.3.3/build
 - rm systemc-2.3.3.tar.gz
 - cd RISC-V-TLM
